#!/bin/bash

# Parameters
PYTHON3=python3

declare -i i=1
declare -i j=1
declare -i k=1
declare -i nbclauses=1
declare -i nbvar=1
declare -i max_complexity=1
declare -i cur_complexity=1
declare -i var1=1
declare -i var2=1
declare -i size=1
declare -i nb_label=1
declare -i starting_nb_clauses=3

# Choose the right directory
DIR=.

echo "Usage : sh up_filter.sh filename_input max_complexity"
file_in=$1
filename=$1
echo "File to be filtred : $file_in"
max_complexity=$2
echo "Maximum complexity = 2^$max_complexity"



size=`wc -l $file_in |awk -F" " '{print $1}'|bc`
echo "Size of $file_in = "$size

nbclauses=`grep -v "c " $file_in|grep "p "|awk -F" " '{print $4}'|bc`
nbvars=`grep -v "c " $file_in|grep "p "|awk -F" " '{print $3}'|bc`

echo "Number of variables = $nbvars"
echo "Number of clauses =  $nbclauses"

echo " c File generated by up_filter_clauses.sh " > $filename.up
echo " p cnf $nbvars $starting_nb_clauses " >> $filename.up
tail -n $starting_nb_clauses $file_in  >> $filename.up

i=`echo "$starting_nb_clauses + 1"|bc`

while [ $i -lt $nbclauses ]; do
    echo "=========================="
    echo "Output for $i clauses"
    echo "=========================="
    tail -n+3 $filename.up |sed '/^\s*$/d' >  $filename.up_temp
    j=`wc -l $filename.up_temp | awk -F" " '{print $1}'|bc`
    if [ $i -lt $nbclauses ]
    then
	j=`echo "$j + 1"|bc`
    fi
    echo " c Output file from up_filter_clauses.sh " >  $filename.up
    echo " p cnf $nbvars $j " >>  $filename.up
    tail -n $i $file_in |head -n 1 |grep -v "p " |grep -v "c " >> $filename.up
    cat $filename.up_temp >> $filename.up
    $PYTHON3 ../compute_W/compute_W.py $filename.up > output2.temp
    cat output2.temp
    cur_complexity=`tail -n 1 output2.temp |awk -F" " '{print $4}'|bc`
    var_filtred=`head -n 3 $filename.up | tail -n 1 | awk -F" " '{print $1}'|bc`
    if [ $var_filtred -lt 0 ]
    then
	var_filtred=`echo "$var_filtred * -1"|bc`
    fi
    echo "Current complexity for $i clauses" >> output.log
    cat output2.temp >> output.log
    if [  $cur_complexity -gt $max_complexity  ]
	then
	echo "Maximal complexity over passed !" >> output.log
	echo "Suppressing the last added clause with var $var_filtred" >> output.log
	sed "3d" $filename.up > $filename.up_temp
	k=`wc -l $filename.up_temp | awk -F" " '{print $1}'|bc`
	k=`echo "$k - 2"|bc`
	sed "2 s/^.*/p cnf $nbvars $k/" $filename.up_temp > $filename.up
    fi
    
    i+=1
done

rm $filename.up_temp
rm output2.temp
rm output.log

echo "Done. Output in $filename.up"
